project:
  type: website

execute:
  freeze: auto

website:
  favicon: /img/favicon.ico
  title: "golemverse"
  search: true
  site-url: https://www.golemverse.org
  description: "Welcome to the golemverse!"
  navbar:
    left:
      - text: "Resources"
        file: resources/index.qmd
      - text: "Packages"
        file: packages/index.qmd
      - text: "Roadmap"
        file: roadmap/index.qmd
      - text: "News"
        file: news/index.qmd
      - text: "Stream"
        file: stream/index.qmd
      - text: "Contact"
        file: index.qmd#contact
    right:
      - icon: github
        href: https://github.com/topics/golemverse
      - icon: twitter
        href: https://twitter.com/thinkr_fr
      - icon: rss
        href: index.xml
  page-footer:
    left:
      - text: "Website built with Quarto"
        href: https://quarto.org
    center:
      - text: "© ThinkR - A French company of R experts"
        href: https://rtask.thinkr.fr

format:
  html:
    theme: simplex
    css: styles.css



