on:
  push:
    branches:
      - main
      - master

name: blogdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Install blogdown
        run: |
          R -e 'install.packages("blogdown")'

      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.60.1")'

      - name: Build site
        run: |
          R -e 'blogdown::build_site(TRUE)'

      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: public
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GITHUB_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: public # optional
         # Destination path
         path: public # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
       with:
         email: ${{ secrets.EMAIL }}
         build_dir: public  # optional
         cname: golemverse.org # optional
